from pathlib import Path

OUTPUT_DIR = Path("output")

BASE_DOMAIN = "https://mon-vie-via.businessfrance.fr"
SEARCH_API_URL = "https://civiweb-api-prd.azurewebsites.net/api/Offers/search"

BATCH_SIZE = 50

TARGET_COUNTRIES: set[str] = {
    # Asia
    "singapour", "singapore",
    "japon", "japan",
    "coree du sud", "south korea", "korea",
    "chine", "china",
    "inde", "india",
    "thailande", "thailand",
    "vietnam", "viet nam",
    "hong kong",
    "taiwan",
    "malaisie", "malaysia",
    "indonesie", "indonesia",
    "philippines",
    "australie", "australia",
    "nouvelle-zelande", "new zealand",
    # North America
    "etats-unis", "united states", "usa",
    "canada",
    # South America
    "bresil", "brazil",
    "argentine", "argentina",
    "mexique", "mexico",
    "colombie", "colombia",
    "chili", "chile",
    "perou", "peru",
    "uruguay",
}

PROFILE_KEYWORDS: list[str] = [
    # --- Target roles ---
    "data scientist",
    "data science consultant",
    "ai engineer",
    "artificial intelligence engineer",
    "ml engineer",
    "machine learning engineer",
    "applied scientist",
    "research scientist",
    "solutions architect",
    "solution architect",
    "associate solutions architect",
    "associate solution architect",
    "ai/ml solutions architect",
    "ai ml solutions architect",
    "ml solutions architect",
    "data solutions architect",
    "cloud solutions architect",
    "technical architect",
    "pre sales engineer",
    "pre-sales engineer",
    "presales engineer",
    "solutions engineer",
    "solution engineer",
    "sales engineer",
    "technical pre-sales",
    "technical presales",
    "forward deployed engineer",
    "forward-deployed engineer",
    "fde",
    "customer success engineer",
    "customer success architect",
    "customer engineer",
    "customer architect",
    "technical account manager",
    "ai consultant",
    "data consultant",
    "ml consultant",
    "technology consultant",
    "technical consultant",
    "consultant ia",
    "consultant data",
    "consultant technique",
    "ingenieur ia",
    "ingenieur machine learning",
    "ingenieur avant vente",
    "architecte solutions",
    "architecte solution",
    "architecte data",
    "architecte cloud",
    "architecte ia",
    # --- Customer-facing / consulting signals ---
    "pre sales",
    "pre-sales",
    "presales",
    "avant vente",
    "avant-vente",
    "customer success",
    "client success",
    "solution design",
    "solution architecture",
    "technical discovery",
    "discovery workshop",
    "requirements gathering",
    "needs assessment",
    "proof of concept",
    "poc",
    "demo",
    "demonstration",
    "workshop",
    "technical enablement",
    "stakeholder management",
    "client-facing",
    "customer-facing",
    "enterprise architecture",
    "cloud architecture",
    "data architecture",
    "ai architecture",
    "ml architecture",
    "consulting",
    "conseil",
    "conseil en technologie",
    "cadrage",
    "recueil des besoins",
    "relation client",
    # --- Core AI / ML ---
    "machine learning",
    "ml",
    "deep learning",
    "artificial intelligence",
    "ai",
    "data science",
    "mlops",
    "llmops",
    "computer vision",
    "nlp",
    "natural language processing",
    "llm",
    "large language model",
    "generative ai",
    "gen ai",
    "fine-tuning",
    "finetuning",
    "embeddings",
    "vector database",
    "semantic search",
    "retrieval",
    "rag",
    "classification",
    "regression",
    "clustering",
    "predictive modeling",
    "predictive modelling",
    "statistical modeling",
    "statistical modelling",
    "data mining",
    "model evaluation",
    "model monitoring",
    "responsible ai",
    "ai governance",
    "guardrails",
    # --- Agentic / LLM tooling ---
    "agentic",
    "agent",
    "multi-agent",
    "langchain",
    "langgraph",
    "langsmith",
    "llamaindex",
    "strands",
    "openai",
    "anthropic",
    "gpt",
    "claude",
    "mistral",
    "llama",
    "prompt engineering",
    "function calling",
    "tool use",
    "ai agents",
    "agentic ai",
    # --- ML frameworks ---
    "pytorch",
    "tensorflow",
    "huggingface",
    "hugging face",
    "autogluon",
    "scikit-learn",
    "sklearn",
    "xgboost",
    "lightgbm",
    "pandas",
    "numpy",
    "scipy",
    "jupyter",
    # --- Languages & core tools ---
    "python",
    "sql",
    "bash",
    "javascript",
    "typescript",
    # --- Backend / API ---
    "fastapi",
    "api",
    "graphql",
    "microservices",
    "backend",
    # --- Frontend / fullstack ---
    "react",
    "next.js",
    "nextjs",
    "streamlit",
    "gradio",
    # --- Cloud & infra ---
    "cloud",
    "serverless",
    "docker",
    "kubernetes",
    "ci/cd",
    "mlflow",
    "terraform",
    "infrastructure as code",
    # AWS
    "aws",
    "amazon web services",
    "sagemaker",
    "amazon sagemaker",
    "bedrock",
    "amazon bedrock",
    "lambda",
    "s3",
    "cloudwatch",
    "ec2",
    "ecs",
    "eks",
    "dynamodb",
    "rds",
    # Azure
    "azure",
    "azure openai",
    "azure ml",
    "azure functions",
    "azure devops",
    "cosmos db",
    # GCP
    "gcp",
    "google cloud",
    "bigquery",
    "vertex ai",
    "google vertex ai",
    "cloud run",
    "pubsub",
    # nuage (French)
    "nuage",
    "informatique en nuage",
    # --- Data engineering ---
    "data engineer",
    "data analyst",
    "data pipeline",
    "big data",
    "spark",
    "databricks",
    "snowflake",
    "redshift",
    "kafka",
    "airflow",
    "dbt",
    "etl",
    "elt",
    "data warehouse",
    "data lake",
    "lakehouse",
    "postgresql",
    "mongodb",
    "redis",
    "elasticsearch",
    "analytics",
    "business intelligence",
    "bi",
    "dashboard",
    "dashboards",
    "data storytelling",
    # --- Forecasting / supply chain ---
    "forecasting",
    "time series",
    "supply chain",
    "demand planning",
    "inventory",
    "logistics",
    "ddmrp",
    "recommendation system",
    # --- Automation (software / AI context) ---
    "automation",
    "process automation",
    "workflow automation",
    "intelligent automation",
    "hyperautomation",
    "rpa",
    "robotic process automation",
    "no-code",
    "low-code",
    "automl",
    "auto ml",
    "model deployment",
    "model serving",
    "feature engineering",
    "feature store",
    "data visualization",
    "tableau",
    "power bi",
    # --- French equivalents ---
    "intelligence artificielle",
    "apprentissage automatique",
    "apprentissage profond",
    "traitement du langage",
    "vision par ordinateur",
    "donnees",
    "ingenieur donnees",
    "science des donnees",
    "modele",
    "infrastructure",
    "chaine logistique",
    "prevision",
    "optimisation",
    "developpeur",
    "ingenieur",
    "architecte",
    "automatisation",
    "automatisation des processus",
    "automatisation intelligente",
    "ia generative",
    "deploiement de modele",
    "visualisation de donnees",
    "analyse de donnees",
    "modelisation",
    "statistiques",
]
