from pathlib import Path

OUTPUT_DIR = Path("output")

BASE_DOMAIN = "https://mon-vie-via.businessfrance.fr"
SEARCH_API_URL = "https://civiweb-api-prd.azurewebsites.net/api/Offers/search"

BATCH_SIZE = 50

TARGET_COUNTRIES: set[str] = {
    # Asia
    "singapour", "singapore",
    "japon", "japan",
    "coree du sud", "south korea", "korea",
    "chine", "china",
    "inde", "india",
    "thailande", "thailand",
    "vietnam", "viet nam",
    "hong kong",
    "taiwan",
    "malaisie", "malaysia",
    "indonesie", "indonesia",
    "philippines",
    "australie", "australia",
    "nouvelle-zelande", "new zealand",
    # North America
    "etats-unis", "united states", "usa",
    "canada",
    # South America
    "bresil", "brazil",
    "argentine", "argentina",
    "mexique", "mexico",
    "colombie", "colombia",
    "chili", "chile",
    "perou", "peru",
    "uruguay",
}

PROFILE_KEYWORDS: list[str] = [
    # --- Core AI / ML ---
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "mlops",
    "computer vision",
    "nlp",
    "natural language processing",
    "llm",
    "large language model",
    "generative ai",
    "gen ai",
    "fine-tuning",
    "finetuning",
    "embeddings",
    "vector database",
    "semantic search",
    "retrieval",
    "rag",
    # --- Agentic / LLM tooling ---
    "agentic",
    "agent",
    "multi-agent",
    "langchain",
    "langgraph",
    "langsmith",
    "strands",
    "openai",
    "anthropic",
    "gpt",
    "prompt engineering",
    "function calling",
    "tool use",
    # --- ML frameworks ---
    "pytorch",
    "tensorflow",
    "huggingface",
    "autogluon",
    "scikit-learn",
    # --- Languages & core tools ---
    "python",
    "sql",
    "bash",
    "javascript",
    "typescript",
    # --- Backend / API ---
    "fastapi",
    "api",
    "graphql",
    "microservices",
    "backend",
    # --- Frontend / fullstack ---
    "react",
    "next.js",
    "nextjs",
    "streamlit",
    "gradio",
    # --- Cloud & infra ---
    "cloud",
    "serverless",
    "docker",
    "kubernetes",
    "ci/cd",
    "mlflow",
    "terraform",
    "infrastructure as code",
    # AWS
    "aws",
    "sagemaker",
    "bedrock",
    "lambda",
    "s3",
    "cloudwatch",
    "ec2",
    "ecs",
    "eks",
    "dynamodb",
    "rds",
    # Azure
    "azure",
    "azure openai",
    "azure ml",
    "azure functions",
    "azure devops",
    "cosmos db",
    # GCP
    "gcp",
    "google cloud",
    "bigquery",
    "vertex ai",
    "cloud run",
    "pubsub",
    # nuage (French)
    "nuage",
    "informatique en nuage",
    # --- Data engineering ---
    "data engineer",
    "data analyst",
    "data scientist",
    "data pipeline",
    "big data",
    "spark",
    "kafka",
    "airflow",
    "dbt",
    "etl",
    "data warehouse",
    "data lake",
    "postgresql",
    "mongodb",
    "redis",
    "elasticsearch",
    # --- Forecasting / supply chain ---
    "forecasting",
    "time series",
    "supply chain",
    "demand planning",
    "inventory",
    "logistics",
    "ddmrp",
    "recommendation system",
    # --- Automation (software / AI context) ---
    "automation",
    "process automation",
    "workflow automation",
    "intelligent automation",
    "hyperautomation",
    "rpa",
    "robotic process automation",
    "no-code",
    "low-code",
    "automl",
    "auto ml",
    "model deployment",
    "model serving",
    "feature engineering",
    "feature store",
    "data visualization",
    "tableau",
    "power bi",
    # --- French equivalents ---
    "intelligence artificielle",
    "apprentissage automatique",
    "apprentissage profond",
    "traitement du langage",
    "vision par ordinateur",
    "donnees",
    "ingenieur donnees",
    "science des donnees",
    "modele",
    "infrastructure",
    "chaine logistique",
    "prevision",
    "optimisation",
    "developpeur",
    "ingenieur",
    "architecte",
    "automatisation",
    "automatisation des processus",
    "automatisation intelligente",
    "ia generative",
    "deploiement de modele",
    "visualisation de donnees",
    "analyse de donnees",
    "modelisation",
    "statistiques",
]
